services:
  _defaults:
    autowire: true
    autoconfigure: true

  JoliCode\Elastically\Transport\HttpClientTransport: ~
  JoliCode\Elastically\Messenger\IndexationRequestHandler: ~
  JoliCode\Elastically\Client:
    arguments:
      $config:
        host: '%env(ELASTICSEARCH_HOST)%'
        port: '%env(ELASTICSEARCH_PORT)%'
        transport: '@JoliCode\Elastically\Transport\HttpClientTransport'
        elastically_index_class_mapping:
          anime: App\Model\Anime
        elastically_mappings_directory: '%kernel.project_dir%/config/elasticsearch'
        elastically_serializer: '@serializer'
        elastically_bulk_size: 100
      $logger: '@logger'

  JoliCode\Elastically\Messenger\DocumentExchangerInterface:
    alias: App\Elasticsearch\DocumentExchanger
