DateTime:
  type: custom-scalar
  config:
    description: 'A string containing a datetime.'
    serialize: ["App\\GraphQL\\Type\\DateTimeType", 'serialize']
    parseValue: ["App\\GraphQL\\Type\\DateTimeType", 'parseValue']
    parseLiteral: ["App\\GraphQL\\Type\\DateTimeType", 'parseLiteral']